### ISSUE TITLE
Debiasing Embeddings 问题

### ISSUE THREAD

**Issue by wwen101** [owenzx/LexicalDebias-ACL2020#1]
您好，我想问下论文中的Debiasing Embeddings方案中Debias Network的label是不同的域吗，还是和Main Model的label1一样？
还有emb cond和sgl sent是什么模型呢，我看论文中并没有介绍？

**Comment by owenzx** [comment]
1. Debias Network的label和Main Model的label是一样的。
2. emb_cond就是4.2节正文中描述的方法，sgl_sent我发现确实是我笔误了，应该是ind_sent，在4.2节的最后有介绍到，感谢提醒！
